name: DyNetAnTutorial

channels:
  - conda-forge
  - defaults

dependencies:
    - python >=3.9.*, <3.11 # Numba only supports python < 3.11
    - pip>=20.*
    - jupyter
    - ipywidgets <8 # Prevents NGL View issue 1032
    - rpy2
    - r-data.table
    - r-ggplot2
    - r-ggrepel
    - r-gdata
    - r-rcolorbrewer
    - r-colorramps
    - r-rpref
    - pip:
        - dynetan>=2.*

