name: DyNetAnTutorial

channels:
  - conda-forge
  - defaults

dependencies:
    - python >=3.9.*
    - pip>=20.*
    - jupyter
    - ipywidgets
    - rpy2
    - r-data.table
    - r-ggplot2
    - r-ggrepel
    - r-gdata
    - r-rcolorbrewer
    - r-colorramps
    - r-rpref
    - pip:
        - dynetan>=2.*

